on:
  pull_request:
    branches:
      - master

name: master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pull
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}
      - name: installpython
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: execute pytest
        run: |
          pip install pytest
          pytest -s